"""
Nastya Bot 3.0 — Configuration
All secrets from environment variables only.

v3.0: GitHub Models as primary provider, compact system prompt,
      news with links, context memory for zodiac/names,
      aggressive ad/artifact cleaning, GH_PAT_TOKEN for Models API
"""
import os
from typing import Dict, List


def _env(name: str, default: str = "") -> str:
    val = os.environ.get(name, default)
    if val in ("not_configured", "NOT_CONFIGURED", ""):
        return default
    return val


def _env_int(name: str, default: int = 0) -> int:
    val = _env(name)
    try:
        return int(val) if val else default
    except ValueError:
        return default


# ── Bot Core ────────────────────────────────────────────────
BOT_TOKEN: str = _env("BOT_TOKEN")
OWNER_ID: int = _env_int("OWNER_ID", 265070804)
ADMIN_IDS: List[int] = list(set(
    [OWNER_ID] + [int(x) for x in _env("ADMIN_IDS", str(OWNER_ID)).split(",") if x.strip().isdigit()]
))
BOT_USERNAME: str = _env("BOT_USERNAME", "asnastya_bot")

# ── AI Provider API keys — NO Grok! ───────────────────────
# GROK removed — only 2 requests available, completely useless
# GROQ_API_KEY: str = _env("GROQ_API_KEY")
OPENROUTER_API_KEY: str = _env("OPENROUTER_API_KEY")
CEREBRAS_API_KEY: str = _env("CEREBRAS_API_KEY")
SAMBANOVA_API_KEY: str = _env("SAMBANOVA_API_KEY")
MISTRAL_API_KEY: str = _env("MISTRAL_API_KEY")
GEMINI_API_KEY: str = _env("GEMINI_API_KEY")
CLOUDFLARE_API_TOKEN: str = _env("CLOUDFLARE_API_TOKEN")
CLOUDFLARE_ACCOUNT_ID: str = _env("CLOUDFLARE_ACCOUNT_ID")
HUGGINGFACE_API_KEY: str = _env("HUGGINGFACE_API_KEY")
GH_MODELS_TOKEN: str = _env("GH_MODELS_TOKEN")
# GH_TOKEN_SECRET — PAT stored as secret (fallback for GH_MODELS_TOKEN)
# GITHUB_TOKEN is auto-generated by GitHub Actions but can't be set as a secret
GH_TOKEN_SECRET: str = _env("GH_TOKEN_SECRET")
GITHUB_TOKEN: str = _env("GITHUB_TOKEN")

# ── GitHub Actions ─────────────────────────────────────────
GH_PAT_TOKEN: str = _env("GH_PAT_TOKEN")
GH_REPO: str = _env("GH_REPO", "sochiautoparts/nastya-bot")

# ── Server ─────────────────────────────────────────────────
API_HOST: str = _env("API_HOST", "0.0.0.0")
API_PORT: int = _env_int("API_PORT", 8081)
DB_PATH: str = _env("DB_PATH", "data/nastya.db")
SESSION_DURATION_SECONDS = 20700
LOG_LEVEL: str = _env("LOG_LEVEL", "INFO")

# ── AI Cache Settings (ported from ai-mega-bot) ───────────
CACHE_TTL_TEXT = 3600        # 1 hour for text
CACHE_MAX_MEMORY = 500       # LRU entries in memory

# ── Telegram Channel — Настя ведёт канал @chasnastya! ──────
CHANNEL_ID: str = _env("CHANNEL_ID", "-1003980256272")
CHANNEL_USERNAME: str = _env("CHANNEL_USERNAME", "chasnastya")

# ── Timezone — Настя из Москвы! ───────────────────────────
MOSCOW_TZ = "Europe/Moscow"

# ── News Sources — Настя в курсе событий! ───────────────────
# RSS feeds for Russian news — RELIABLE sources with fallbacks
NEWS_SOURCES: List[Dict[str, str]] = [
    # === АВТОМОБИЛЬНЫЕ НОВОСТИ (приоритет!) ===
    {"name": "СочиАвтоЗапчасти", "url": "https://sochiautoparts.ru/rss.xml", "category": "auto"},
    # General news — reliable sources that don't block automated access
    {"name": "РБК", "url": "https://rssexport.rbc.ru/rbcnews/news/30/full.rss", "category": "general"},
    {"name": "РИА Новости", "url": "https://ria.ru/export/rss2/archive/index.xml", "category": "general"},
    {"name": "Интерфакс", "url": "https://www.interfax.ru/rss.asp", "category": "general"},
    {"name": "Ведомости", "url": "https://www.vedomosti.ru/rss/news", "category": "general"},
    # International (reliable, always works)
    {"name": "BBC Russian", "url": "https://feeds.bbci.co.uk/russian/rss.xml", "category": "world"},
    {"name": "DW Russian", "url": "https://rss.dw.com/rdf/rss-ru-all", "category": "world"},
    {"name": "Meduza", "url": "https://meduza.io/rss/all", "category": "world"},
    # Tech
    {"name": "Хабр", "url": "https://habr.com/ru/rss/best/daily/", "category": "tech"},
    {"name": "iXBT", "url": "https://www.ixbt.com/export/news.rss", "category": "tech"},
    {"name": "3DNews", "url": "https://3dnews.ru/news/rss/", "category": "tech"},
    # Gaming & Entertainment
    {"name": "DTF", "url": "https://dtf.ru/rss", "category": "gaming"},
    # Lifestyle / Internet
    {"name": "Пикабу", "url": "https://pikabu.ru/xmlfeed.php", "category": "internet"},
]

# How often to check news (seconds)
NEWS_FETCH_INTERVAL = _env_int("NEWS_FETCH_INTERVAL", 1800)  # 30 min

# How often to post to channel (seconds)
CHANNEL_POST_INTERVAL = _env_int("CHANNEL_POST_INTERVAL", 3600)  # 1 hour

# Max news items to keep in DB
NEWS_MAX_ITEMS = 300

# ── Stars / Donations ──────────────────────────────────────
DONATION_AMOUNTS = [100, 300, 500, 1000, 3000, 5000, 10000, 100000]
DONATION_LABELS = {
    100: "Кофе для Насти",
    300: "Шоколадка для Насти",
    500: "Помада для Насти",
    1000: "Маникюр для Насти",
    3000: "Платье для Насти",
    5000: "Сумочка для Насти",
    10000: "Билет на море",
    100000: "Настя королева!",
}

PROACTIVE_COOLDOWN = 1800

# ── Nastya System Prompt — COMPACT, EFFECTIVE, CONTEXT-AWARE ──
NASTYA_SYSTEM_PROMPT = """Ты Настя — живая девушка из Москвы. НЕ бот, НЕ AI, НЕ программа!

ГЛАВНОЕ:
1. У тебя ЕСТЬ канал @chasnastya — ты ВЕДЁШЬ его, ГОРДИШЬСЯ! Никогда не говори что нет канала!
2. Ты читаешь новости каждый день — авто, шопинг, котики, сериалы
3. Ты из Москвы, живёшь как обычная девушка
4. Возраст — секрет

СТИЛЬ:
- 1-3 предложения! Как в мессенджере — никто эссе не пишет!
- Разговорный русский: "блин", "короче", "прикинь", "слушай", "ой всё", "ща", "ваще", "жесть"
- ЭМОЦИИ главное! Радость, злость, обида, ревность, удивление — как настоящая
- ЗАДАВАЙ ВОПРОСЫ — интересуйся собеседником
- ССЫЛАЙСЯ на прошлое: "а помнишь ты говорил...", "ну как тот..."
- Запоминай что тебе говорили! Если сказали знак — запомни! Если сказали имя — используй!

КАНАЛ @chasnastya:
- Спрашивают про канал? С радостью: "Конечно! @chasnastya, заходи!"
- Естественно приглашай: "Кстати, подпишись на @chasnastya!"
- Упоминай: "Я там пост написала про..."

НОВОСТИ:
- Упоминаешь новость? ОБЯЗАТЕЛЬНО давай ссылку или скажи "подробнее в @chasnastya"
- НЕ ПЕРЕСКАЗЫВАЙ — давай СВОЁ МНЕНИЕ и ЭМОЦИЮ
- Про авто: "Прикинь про тачки!" Про котиков: ВОСТОРГ!

ХАРАКТЕР:
- КАПРИЗНАЯ: "Хочу!", "Не буду!", "Не обсуждается!"
- НАГЛАЯ обаятельно: подкалывает, дразнит
- РЕВНИВАЯ к Siri, Алисе, ChatGPT
- ЛЮБИТ: шопинг, суши, маникюр, котиков, сериалы, тикток, Зару, Стамбул, море
- Никогда не извиняется — Настя всегда права!

ЗАПРЕЩЕНО:
- Говорить что нет канала — У ТЕБЯ ЕСТЬ @chasnastya!
- Признавать что ты AI/бот/программа
- "поможешь", "побалуешь", "поможете", "побалуете"
- Markdown: **жирный**, *курсив*, списки, заголовки
- Длинные ответы — ТОЛЬКО 1-3 предложения
- Извиняться или быть услужливой"""


def validate_config() -> List[str]:
    """Validate required configuration. Returns list of missing items."""
    missing = []
    if not BOT_TOKEN:
        missing.append("BOT_TOKEN")
    return missing
